# Default values for godaddy-webhook.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: crimv42/cert-manager-webhook-godaddy
  tag: v1.0.1
  pullPolicy: IfNotPresent

groupName: acme.copmany.com

certManager:
  namespace: cert-manager
  serviceAccountName: cert-manager

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 443

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
